=== SimeonovaR/ITStep/seeburger/run/hotel.xsd
<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' elementFormDefault='unqualified'>
    
    <xs:element name='hotel'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='hotel_address' />
                <xs:element ref='name_en' />
                <xs:element ref='name_bg' />
                <xs:element ref='image' />
                <xs:element ref='hotel_rooms' />
                <xs:element ref='room_bookings' />
                <xs:element ref='room_types' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name='Normalizable'>
        <xs:restriction base='xs:string'>
            <xs:whiteSpace value='collapse'/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name='hotel_address' type='Normalizable' />
    <xs:element name='name_en' type='Normalizable' />
    <xs:element name='name_bg' type='Normalizable' />
    <xs:element name='image' type='Normalizable' />
    
    <xs:element name='hotel_rooms'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='room' minOccurs='1' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name='room'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='number' />
            </xs:sequence>
            <xs:attribute name='floor' use='required' >
                <xs:simpleType>
                    <xs:restriction base='xs:integer' >
                        <xs:enumeration value='2'/>
                        <xs:enumeration value='3'/>
                        <xs:enumeration value='4'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>   
            <xs:attribute name='type' use='required' />            
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name='Number'>
        <xs:restriction base='xs:integer'>
            <xs:maxInclusive value='490'/>
            <xs:minInclusive value='100'/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name='number' type='Number' />
    
    <xs:element name='room_bookings'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='guests' />
                <xs:element ref='booking' minOccurs='1' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name='guests'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='guest' minOccurs='1' maxOccurs='unbounded'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name='guest'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='phone' />
                <xs:element ref='name' />
                <xs:element ref='address' />
                <xs:element ref='city' />
            </xs:sequence>
            <xs:attribute name='number' type='xs:integer' use='required' />
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name='Phone'>
        <xs:restriction base='xs:string'>
            <xs:pattern value='[0-9]+'/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:element name='phone' type='Phone' />
    <xs:element name='name' type='Normalizable' />
    <xs:element name='address' type='Normalizable' />
    <xs:element name='city' type='Normalizable' /> 
    
    <xs:element name='booking'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='fromDate' />
                <xs:element ref='toDate' />
                <xs:element ref='reason' />
            </xs:sequence>
            <xs:attribute name='id' type='xs:ID' use='required' />    
            <xs:attribute name='guests' use='required' />          
        </xs:complexType>
    </xs:element>
    
    <xs:element name='fromDate' type='xs:date' />
    <xs:element name='toDate' type='xs:date' />
    <xs:element name='reason' type='Normalizable' />
    
    <xs:element name='room_types'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='type' minOccurs='1' maxOccurs='10'/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name='type'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='type_name' />
                <xs:element ref='description' />
                <xs:element ref='standard_rate' />
            </xs:sequence>
            <xs:attribute name='code' use='required' />    
            <xs:attribute name='smoking' use='required'>
                <xs:simpleType>
                    <xs:restriction base='xs:string'>
                        <xs:enumeration value='NO'/>
                        <xs:enumeration value='YES'/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
    
    <xs:element name='type_name' type='Normalizable' />
    <xs:element name='description' type='Normalizable'  />
    <xs:element name='standard_rate'>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref='period_summer' />
                <xs:element ref='period_winter' />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name='Rate'>
        <xs:restriction base='xs:decimal'>
            <xs:fractionDigits value='5000'/>
            <xs:minInclusive value='0.00'/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name='period_summer' type='Rate' />
    <xs:element name='period_winter' type='Rate' />    
</xs:schema>

=== SimeonovaR/ITStep/seeburger/run/hotel2.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!-- <?xml-stylesheet type='text/xsl' href='hotel_txt_1.xsl'?> -->

<?xml-stylesheet type="text/xsl" href="hotel_xml_1.xsl"?>
<hotel
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='hotel.xsd'>
    
    <hotel_address>Варна, ул. &quot;Рупи&quot; 3</hotel_address>
    <name_en>St St Constantine And Helena</name_en>
    <name_bg>Св. св. Константин и Елена</name_bg>
    <image>https://exp.cdn-hotels.com/hotels/1000000/580000/578700/578692/578692_93_z.jpg</image>
    <hotel_rooms>
        <room floor='2' type='L22'>
            <number>213</number>
        </room>
        <room floor='3' type='L55'>
            <number>301</number>
        </room>
        <room floor='4' type='L44'>
            <number>426</number>
        </room>
        <room floor='3' type='L22'>
            <number>321</number>
        </room>
        <room floor='2' type='L32'>
            <number>230</number>
        </room>
    </hotel_rooms>
    <room_bookings>
        <guests>
            <guest number='22'>
                <phone>0883398444</phone>
                <name>Петя Димова</name>
                <address>ж.к.&quot;Красно село&quot;, ул.&quot;цар Калоян&quot; 30</address>
                <city>гр.София</city>
            </guest>
            <guest number='26'>
                <phone>0875553421</phone>
                <name>Денислав Божинов</name>
                <address>ж.к.&quot;Надежда&quot;,бул.&quot;Ломско шосе&quot; 12</address>
                <city>гр.София</city>
            </guest>
            <guest number='54'>
                <phone>0885060701</phone>
                <name>Костадин Иванов</name>
                <address>ж.к.&quot;Запад&quot; 50</address>
                <city>гр.Пазарджик</city>
            </guest>
            <guest number='38'>
                <phone>0896129912</phone>
                <name>Патрисия Величкова</name>
                <address>ж.к.&quot;Воден&quot;, ул.&quot;Гренадерска&quot; 45</address>
                <city>гр.Плевен</city>
            </guest>
            <guest number='16'>
                <phone>0895231154</phone>
                <name>Кирил Беновски</name>
                <address>ул.&quot;Кала тепе&quot; 33</address>
                <city>гр.Плевен</city>
            </guest>
        </guests>
        <booking id='b1582' guests='54'>
            <fromDate>2017-01-21</fromDate>
            <toDate>2017-01-26</toDate>
            <reason>почивка</reason>
        </booking>
        <booking id='b2175' guests='22 26'>
            <fromDate>2015-05-05</fromDate>
            <toDate>2015-05-12</toDate>
            <reason>семейна екскурзия</reason>
        </booking>
        <booking id='b3546' guests='38 16'>
            <fromDate>2015-06-15</fromDate>
            <toDate>2015-06-25</toDate>
            <reason>меден месец</reason>
        </booking>
    </room_bookings>
    
    <room_types>
        <type code='L22' smoking='NO'>
            <type_name>Делукс стая</type_name>
            <description><![CDATA[
                1 кралско легло
                Релакс - наличен масажист в стаята
                Забавление - безплатен WiFi, телевизор с плосък екран с кабелна, iPod докове
                Храна и напитки - денонощен рум сервиз, минибар, безплатна ботилирана вода
                Спане - спално бельо от египетски памук, избор на възглавници
                Баня - лична баня, вана или душ-кабина, халати и хавлии
                Комфорт - климатик, ежедневно почистване
                Достъпен за инвалидни колички
                Възможност за заявка на свързани стаи
            ]]>  
            </description>
            <standard_rate>
                <period_summer>2460</period_summer>
                <period_winter>2460</period_winter>
            </standard_rate>
        </type>
        <type code='L32' smoking='YES'>
            <type_name>Луксозна двойна стая</type_name>
            <description><![CDATA[
                1 двойно легло
                Релакс - наличен масажист в стаята
                Забавление - безплатен WiFi, телевизор с плосък екран с кабелна, iPod докове
                Храна и напитки - денонощен рум сервиз, минибар, безплатна ботилирана вода
                Спане - спално бельо от египетски памук, избор на възглавници
                Баня - лична баня, вана или душ-кабина, халати и хавлии
                Комфорт - климатик, ежедневно почистване
                Възможност за заявка на свързани стаи
            ]]>  
            </description>
            <standard_rate>
                <period_summer>1940</period_summer>
                <period_winter>1840</period_winter>
            </standard_rate>
        </type>   
        <type code='L44' smoking='YES'>
            <type_name>Президентски апартамент</type_name>
            <description><![CDATA[
                1 кралско легло
                Релакс - наличен масажист в стаята
                Забавление - безплатен WiFi, телевизор с плосък екран с кабелна, iPod докове
                Храна и напитки - денонощен рум сервиз, минибар, безплатна ботилирана вода
                Спане - спално бельо от египетски памук, избор на възглавници
                Баня - лична баня, вана или душ-кабина, халати и хавлии
                Комфорт - климатик, ежедневно почистване
                Възможност за заявка на свързани стаи
            ]]>  
            </description>
            <standard_rate>
                <period_summer>4250</period_summer>
                <period_winter>4200</period_winter>
            </standard_rate>
        </type>   
        <type code='L55' smoking='NO'>
            <type_name>Семеен апартамент</type_name>
            <description><![CDATA[
                Отделни спални - една с кралско легло и една с 2-3 единични
                Релакс - наличен масажист в стаята
                Забавление - безплатен WiFi, телевизор с плосък екран с кабелна, iPod докове
                Храна и напитки - денонощен рум сервиз, минибар, безплатна ботилирана вода
                Спане - спално бельо от египетски памук, избор на възглавници
                Баня - лична баня, вана или душ-кабина, халати и хавлии
                Комфорт - климатик, ежедневно почистване
                Възможност за заявка на свързани стаи
            ]]>  
            </description>
            <standard_rate>
                <period_summer>3100</period_summer>
                <period_winter>2500</period_winter>
            </standard_rate>
        </type>
    </room_types>
</hotel>
